# Connect to Standard VM
ssh-keygen -f "<ADDRESS TO YOUR PUBLIC SSH FOLDER>/known_hosts" -R "<STANDARD_VM_EXTERNAL_IP>"
ssh -i <ADDRESS TO YOUR PUBLIC SSH KEY> <YOUR_USERNAME>@<STANDARD_VM_EXTERNAL_IP>

# Connect to CPU-Optimized VM
ssh-keygen -f "<ADDRESS TO YOUR PUBLIC SSH FOLDER>/known_hosts" -R "<CPU_VM_EXTERNAL_IP>"
ssh -i <ADDRESS TO YOUR PUBLIC SSH KEY> <YOUR_USERNAME>@<CPU_VM_EXTERNAL_IP>